# name: git push into another repo to deploy to vercel

# on:
#   push:
#     branches: [main]

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '20'

#       - name: Install dependencies
#         run: yarn install 

#       - name: Build the project
#         run: yarn build

#       - name: Prepare output
#         run: |
#           mkdir -p output
          # cp -r .next/* output/
          
name: git push into another repo to deploy to vercel

on:
  push:
    branches: [main]

jobs:
 build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  
          cache: 'yarn'  

      - name: Check Yarn Version
        run: yarn --version 

      - name: Install dependencies
        run: yarn install --immutable 

      - name: Build the project
        run: yarn build 

      - name: Prepare output
        run: |
          mkdir -p output
          cp -r .next/* output/  # Adjust according to your deployment needs


      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.HANDAGGLE_CCA_FE_KEY }}
        with:
          source-directory: 'output'
          destination-github-username: handaggle
          destination-repository-name: cca-fe
          user-email: ${{ secrets.HANDAGGLE_EMAIL }}
          commit-message: 'Deploying build'
          target-branch: main

      - name: Echo the output directory
        run: echo $DESTINATION_CLONED_DIRECTORY
